// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHG7LNWNMf6ra7rFOTLgqlQzhQXVZGkJ4',
    appId: '1:380658192783:web:ea4f74ca61447fe5e27bfa',
    messagingSenderId: '380658192783',
    projectId: 'notificaciones-abogado',
    authDomain: 'notificaciones-abogado.firebaseapp.com',
    storageBucket: 'notificaciones-abogado.firebasestorage.app',
    measurementId: 'G-31J60BXVWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0UymGVOvGp24BMLL90MzzGDw8dsi0qgY',
    appId: '1:380658192783:android:904cf8e0530d9c5ee27bfa',
    messagingSenderId: '380658192783',
    projectId: 'notificaciones-abogado',
    storageBucket: 'notificaciones-abogado.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPk8Lk4tYSVTZNbPIdPTug6fOt1fWawac',
    appId: '1:380658192783:ios:0645240343198982e27bfa',
    messagingSenderId: '380658192783',
    projectId: 'notificaciones-abogado',
    storageBucket: 'notificaciones-abogado.firebasestorage.app',
    iosBundleId: 'com.example.flutterSw1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPk8Lk4tYSVTZNbPIdPTug6fOt1fWawac',
    appId: '1:380658192783:ios:0645240343198982e27bfa',
    messagingSenderId: '380658192783',
    projectId: 'notificaciones-abogado',
    storageBucket: 'notificaciones-abogado.firebasestorage.app',
    iosBundleId: 'com.example.flutterSw1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHG7LNWNMf6ra7rFOTLgqlQzhQXVZGkJ4',
    appId: '1:380658192783:web:87c45ce5f2f9de4ee27bfa',
    messagingSenderId: '380658192783',
    projectId: 'notificaciones-abogado',
    authDomain: 'notificaciones-abogado.firebaseapp.com',
    storageBucket: 'notificaciones-abogado.firebasestorage.app',
    measurementId: 'G-RDJNBDLCE5',
  );
}
