// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxvbTOAqMO0zHQAiGwwU6r3MzQyc7OPmM',
    appId: '1:570490622645:web:585437f76fac124f7164fc',
    messagingSenderId: '570490622645',
    projectId: 'proyecto-sw1-c8ae5',
    authDomain: 'proyecto-sw1-c8ae5.firebaseapp.com',
    storageBucket: 'proyecto-sw1-c8ae5.firebasestorage.app',
    measurementId: 'G-CJZ16RJK9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGYQ2ALqy36V21XewLal6XSynT7xDSkoY',
    appId: '1:570490622645:android:aec3333007629da67164fc',
    messagingSenderId: '570490622645',
    projectId: 'proyecto-sw1-c8ae5',
    storageBucket: 'proyecto-sw1-c8ae5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgEciTSW9K99URPWJHR67LY-Ji169XZQ4',
    appId: '1:570490622645:ios:0987c129136aae777164fc',
    messagingSenderId: '570490622645',
    projectId: 'proyecto-sw1-c8ae5',
    storageBucket: 'proyecto-sw1-c8ae5.firebasestorage.app',
    iosBundleId: 'com.example.flutterSw1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgEciTSW9K99URPWJHR67LY-Ji169XZQ4',
    appId: '1:570490622645:ios:0987c129136aae777164fc',
    messagingSenderId: '570490622645',
    projectId: 'proyecto-sw1-c8ae5',
    storageBucket: 'proyecto-sw1-c8ae5.firebasestorage.app',
    iosBundleId: 'com.example.flutterSw1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxvbTOAqMO0zHQAiGwwU6r3MzQyc7OPmM',
    appId: '1:570490622645:web:2f948af0fbf852907164fc',
    messagingSenderId: '570490622645',
    projectId: 'proyecto-sw1-c8ae5',
    authDomain: 'proyecto-sw1-c8ae5.firebaseapp.com',
    storageBucket: 'proyecto-sw1-c8ae5.firebasestorage.app',
    measurementId: 'G-LKYYK2X22L',
  );
}
